### ISSUE TITLE
[판매관리] 관리자는 특정 주문 취소내역을 조회할 수 있습니다.

### ISSUE THREAD

**Issue by youngwoo2** [ssg-java3-240304/shop-Kick-n-Go#15]
# 🌈 Success criteria
1. 취소관리-취소-주문 취소내역 조회(CM-01)

# 👷To-do
- [ ] 관리자는 결제 완료된 주문내역 중 취소처리 상태별 취소내역을 조회할 수 있습니다.
- [ ] 관리자는 결제 완료된 주문내역 중 특정 날짜별 취소내역을 조회할 수 있습니다.
- [ ] 관리자는 결제 완료된 주문내역 중 주문번호별 취소내역을 조회할 수 있습니다.

# 👓 Review
1.
