### ISSUE TITLE
[관리자 로그인] 관리자는 로그인할 수 있습니다. 

### ISSUE THREAD

**Issue by tjpark312** [ssg-java3-240304/shop-Kick-n-Go#18]
# 🌈 Success criteria
1. MEM00

# 👷To-do
- [x]  관리자는 /admin/login 페이지를 통해 로그인할 수 있습니다
- [x]  로그인 페이지에는 이메일과 비밀번호 입력 필드가 있어야 합니다.
- [x] 로그인 페이지에는 '로그인'버튼이 있어야 합니다.

# 👓 Review
1.

**Comment by tjpark312** [comment]
로그인 성공 시 

디비에 저장되어 있는 managerEmail , managerPassword 값 입력 
![image](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237157/416f97e9-9df0-455a-b2b8-9ed321d884f9)]

service.compareLoginInfo 를 통해 값이 일치하다면
redirect:/dashboard로 이동 
![image](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237157/e784ffaa-2cc0-4cab-bff0-3b2d9e1979e1)

입력한 값이 null 이라면 ?

![image](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237157/63fbfc71-19e3-45eb-9309-6b686d1d12a3)

NullpointExceptionHandler를 통해 에러 메세지 반환 

![image](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237157/4870f446-28cc-4775-8b59-f78af35473f0)

다시 로그인 하려면 

a href 태그를 통해 로그인 화면으로 이동
