### ISSUE TITLE
[상품관리] 관리자는 상품을 등록할 수 있습니다.

### ISSUE THREAD

**Issue by jeongeun1** [ssg-java3-240304/shop-Kick-n-Go#36]
# 🌈 Success criteria
1. 상품관리/상품등록(PRM-001)
2. 상품 등록시 카테고리, 상품명, 판매가, 사이즈, 컬러, 재고수량, 이미지, 소재를 입력하게 되며, 모두 필수 입력값입니다.
3. 상품 코드와 판매상태는 자동생성됩니다.

# 👷To-do
- [ ] 카테고리는 여성화/남성화/아동화 중 선택할 수 있습니다.
- [ ] 상품명은 필수이며, 100자 이내로 작성할 수 있습니다.
- [ ] 판매가를 입력할 수 있습니다.
- [ ] 사이즈를 입력할 수 있습니다.
- [ ] 컬러를 입력할 수 있습니다.
- [ ] 재고수량은 1 이상의 숫자를 입력 했을시에는 판매중, 0을 입력하면 품절 상태로 자동 설정됩니다.
- [ ] 상품이미지를 첨부할 수 있습니다.
- [ ] 상품소재를 선택할 수 있습니다. (가죽, 합성섬유, 캔버스, 메시, 기타)

# 👓 Review
1.

**Comment by jeongeun1** [comment]
## ✒Description
* 발생한 버그
![에러페이지](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237367/2f244cdf-bb16-4e3d-9650-1c41832b785a)

## ⚒ Reproduction
* 버그 발생시 코드
```java
@PostMapping("/product-regist")
    // 상품등록
    public String regist(@ModelAttribute ProductRegistDto productRegistDto, RedirectAttributes redirectAttributes){
        log.info("POST /product/regist");
        log.debug("productRegistDto = {}", productRegistDto);
        ProductDto productDto = productRegistDto.toProductDto();
        int result = productCommandService.insertProduct(productDto);
//        redirectAttributes.addFlashAttribute("message", "메뉴를 성공적으로 등록했습니다.");
        return "redirect:/product-regist";
    }
``` 

## 🥌Try


## 🔮Solution
* PostMapping을 호출하기 위한 GetMapping메소드 먼저 만들기
![image](https://github.com/ssg-java3-240304/shop-Kick-n-Go/assets/162237367/7e6e10d1-f2f0-41b0-8bd5-01796547f9c0)
