### ISSUE TITLE
[프로젝트 할일 및 일정 관리]

### ISSUE THREAD

**Issue by bisoya** [ssg-java3-240304/shop-Kick-n-Go#40]
# 🌈 Success criteria
1. 

# 👷To-do
- [x] 깃허브 프로젝트 생성
- [x] 깃허브 마일스톤 생성
- [x] 깃허브 이슈 작성 및 담당자 할당
- [x] 깃허브 이슈들을 마일스톤 단위로 묶기
- [x] 깃허브 이슈 작성한 것 강사님께 검토 부탁드리기

# 👓 Review
1.
